### ISSUE TITLE
Clarify licensing of the various assets

### ISSUE THREAD

**Issue by akien-mga** [securas/SealedBite#1]
Congrats on the release! I have yet to try it but it looks amazing :D

I noticed that you have three license files, and it's not clear what each applies to. The main `LICENSE` is MIT so I assume that's what you want the project to be on, unless specified otherwise, but there's also license text for CC-BY-NC-ND and GPL-2.0. Are those for thirdparty assets? If so, this should be mentioned somewhere (e.g. in the README).

**Comment by securas** [comment]
Ops... One License file escaped. It's GPL and CC

**Comment by akien-mga** [comment]
It's still no clear what is GPLv2 and what is CC-BY-NC-ND in the repo.

**Comment by securas** [comment]
Should be clear now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by securas** [comment]
No... Thank you! I know nothing about licenses.

**Comment by throwaway1037** [comment]
Please may the files be released under a [libre](https://freedomdefined.org/Licenses) license?
Some OS distributions such as [Parabola](https://parabola.nu) cannot package games which are not libre.

**Comment by securas** [comment]
> Please may the files be released under a [libre](https://freedomdefined.org/Licenses) license?
> Some OS distributions such as [Parabola](https://parabola.nu) cannot package games which are not libre.

The licenses for code and assets have been defined a long time ago and I have no plans to change.

**Comment by throwaway1037** [comment]
@securas, two years isn't that long in the context of software licensing.
Please can I convince you to change the license to a libre one?
It would be a shame to have this project remain proprietary when it could be enjoyed in freedom on GNU+Linux-libre.

**Comment by securas** [comment]
I'm afraid it is simply not possible for reasons that I will not disclose. Please accept the current license as it is.

**Comment by throwaway1037** [comment]
That's a very cryptic message.

Do you know how to get in contact with the other authors of the files in the game, such as Fabien Merten?
Are there any other authors who hold copyright over the files?

**Comment by securas** [comment]
The message is clear in the sense that I do not wish to release the license to the assets. Please do not insist.

Having said that, you may try to talk to Fabien since he composed the music of the game and may be ok with it being used elsewhere. He has a youtube channel and you may be able to reach him there.

**Comment by throwaway1037** [comment]
Do you realise the extent of the repercussions of making a work proprietary?
Since the length of the term of copyright is extended by lobbyists groups every time lots of works are about to enter the public domain, proprietary works might never be libre.

That means we will never be able to package it for systems which are 100% libre, like [Parabola](https://parabola.nu) or make an entry for it on the [Libre Game Wiki](https://libregamewiki.org).

**Comment by akien-mga** [comment]
@throwaway1037 I think @securas has made their point clearly, and your proselytism is only going to worsen the cause you aim to champion. I've been advocating for FOSS for 15 years myself, and I've seen countless self entitled zealots push developers *away* from FOSS by doing such proselytism.

Please respect creators' choices for their own work. You can inform, but not demand, and much less attempt to guilt trip people with hyperbolic statements.

**Comment by throwaway1037** [comment]
@akien-mga, please stop undermining me and discrediting the concept of freedom.

Falsely labelling advocating for freedom as "proselytism" makes it sound religious or cult-like and easily discreditable on this basis alone.

The term "FOSS" includes "OSS" which also undermines freedom.
[Open source misses the point of freedom.](https://gnu.org/philosophy/open-source-misses-the-point.html)

Thirdly, labelling me as a "self-entitled zealot" when all I am doing is spending my own time politely asking a maintainer to release a project under a libre license for the benefit of other people is also an insult and an attempt to discredit my actions.

Next, the term ["creator"](https://gnu.org/philosophy/words-to-avoid.html#Creator) is heavily biased and once again undermines freedom.

I cannot "respect" a choice I think is morally reprehensible.
Nobody should have the right to make a choice which violates the fundamental freedoms of others.

Claiming politely asking is a "demand" once again undermines my actions.

I am not attempting to "guilt trip" anyone with "hyperbole".
What I stated is true: [see for yourself](https://wikipedia.org/wiki/Mickey_Mouse_Copyright_Act).

Based on all this, I am led to believe that you practise [contradictory support](https://gnu.org/philosophy/contradictory-support.html) and do not actually think all works should be libre.
If you actually believe this and want to help, then please support requests of liberation such as this one, instead of undermining people.
All you've done is confused the poor person who has to read all this and make me spend time correcting your mistakes.

I have given a couple of examples of projects which which welcome new projects into the free world, namely [Parabola](https://parabola.nu), a 100% libre GNU+Linux-libre OS distribution which could package this project if it were libre, and [The Libre Game Wiki](https://libregamewiki.org), which could have an article promoting this game if it were libre.

**Comment by securas** [comment]
Deleted comment for being out of scope.

**Comment by throwaway1037** [comment]
@securas, if you censor my comment again I will report your account.

@akien-mga, please stop undermining me and discrediting the concept of freedom.

Falsely labelling advocating for freedom as "proselytism" makes it sound religious or cult-like and easily discreditable on this basis alone.

The term "FOSS" includes "OSS" which also undermines freedom.
[Open source misses the point of freedom.](https://gnu.org/philosophy/open-source-misses-the-point.html)

Thirdly, labelling me as a "self-entitled zealot" when all I am doing is spending my own time politely asking a maintainer to release a project under a libre license for the benefit of other people is also an insult and an attempt to discredit my actions.

Next, the term ["creator"](https://gnu.org/philosophy/words-to-avoid.html#Creator) is heavily biased and once again undermines freedom.

I cannot "respect" a choice I think is morally reprehensible.
Nobody should have the right to make a choice which violates the fundamental freedoms of others.

Claiming politely asking is a "demand" once again undermines my actions.

I am not attempting to "guilt trip" anyone with "hyperbole".
What I stated is true: [see for yourself](https://wikipedia.org/wiki/Mickey_Mouse_Copyright_Act).

Based on all this, I am led to believe that you practise [contradictory support](https://gnu.org/philosophy/contradictory-support.html) and do not actually think all works should be libre.
If you actually believe this and want to help, then please support requests of liberation such as this one, instead of undermining people.
All you've done is confused the poor person who has to read all this and make me spend time correcting your mistakes.

I have given a couple of examples of projects which which welcome new projects into the free world, namely [Parabola](https://parabola.nu), a 100% libre GNU+Linux-libre OS distribution which could package this project if it were libre, and [The Libre Game Wiki](https://libregamewiki.org), which could have an article promoting this game if it were libre.

**Comment by securas** [comment]
Deleted comment again for being out of scope and harassment.

**Comment by throwaway1037** [comment]
@securas what are you trying to achieve?
Once you've censored me and are left to restrict people, will that bring you happiness?

**Comment by throwaway1037** [comment]
In what way were my comments "harassment"?

**Comment by securas** [comment]
Deleted comment for being out of scope.

**Comment by throwaway1037** [comment]
Seriously? You won't even explain why you are systematically deleting all my comments?

The truth is that they are not "out of scooe" or "harassment"; you just want an excuse to censor my comments so you can continue restricting people without the guilt of looking at my comments.
Why not just release under a libre license?
